'\"
'\" Copyright (C) 1998-2000, Stefan Sinnige.
'\"
'\" This program is free software; you can redistribute it and/or
'\" modify it under the terms of the GNU Lesser General Public
'\" License as published by the Free Software Foundation; either
'\" version 2.1 of the License, or (at your option) any later
'\" version.
'\"
'\" This program is distributed in the hope that it will be
'\" useful, but WITHOUT ANY WARRANTY; without even the implied
'\" warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
'\" PURPOSE. See the GNU Lesser General Public License for more
'\" details.
'\"
'\" You should have received a copy of the GNU Lesser General
'\" Public License along with this program; if not, write to the
'\" Free Software Foundation, Inc., 59 Temple Place, Suite 330,
'\" Boston, MA 02111-1307, USA.
'\"
'\" For the full GNU Lesser General Public License, see the
'\" 'LICENSE' file.
'\"
.TH wishpp 1 2.0 Wishpp "Tclpp Applications"
.BS
.SH NAME
wishpp \- Simple Tcl windowing shell extended with Tclpp commands
.SH SYNOPSIS
\fBwishpp\fR ?\fIfileName arg ...\fR? 
.br
.SH DESCRIPTION
The \fBwishpp\fR is a windowing shell application that reads Tcl, Tk
and Tclpp commands from its standard input or from a file and evaluates them.
If invoked with no arguments then it runs interactively, reading commands
from standard input and printing command results and error messages
to standard output.
It runs until the \fBexit\fR command is invoked or until it
reaches end-of-file on its standard input.
.SH AUTHOR(S)
Stefan Sinnige (ssinnige@geocities.com)
.SH SEE ALSO
tclppsh(1), tclsh(1), wish(1)
